// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBug2U06oK55hKvf4hyextKlH7RNVVTbEo',
    appId: '1:842172225259:web:2ed695116911d6f9f3d0ae',
    messagingSenderId: '842172225259',
    projectId: 'newstream-15e6a',
    authDomain: 'newstream-15e6a.firebaseapp.com',
    storageBucket: 'newstream-15e6a.firebasestorage.app',
    measurementId: 'G-X1MKNR2DQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGIDvXVgPI_kBZSc_ABABaIkWCnrt_pO8',
    appId: '1:842172225259:android:a860b50a759d1050f3d0ae',
    messagingSenderId: '842172225259',
    projectId: 'newstream-15e6a',
    storageBucket: 'newstream-15e6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZuJrtZaYOR89jxigWK_geitxma3cziaM',
    appId: '1:842172225259:ios:aa8458b7998bd13ff3d0ae',
    messagingSenderId: '842172225259',
    projectId: 'newstream-15e6a',
    storageBucket: 'newstream-15e6a.firebasestorage.app',
    iosBundleId: 'com.example.newstream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZuJrtZaYOR89jxigWK_geitxma3cziaM',
    appId: '1:842172225259:ios:aa8458b7998bd13ff3d0ae',
    messagingSenderId: '842172225259',
    projectId: 'newstream-15e6a',
    storageBucket: 'newstream-15e6a.firebasestorage.app',
    iosBundleId: 'com.example.newstream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBug2U06oK55hKvf4hyextKlH7RNVVTbEo',
    appId: '1:842172225259:web:a9c535fa914ee79df3d0ae',
    messagingSenderId: '842172225259',
    projectId: 'newstream-15e6a',
    authDomain: 'newstream-15e6a.firebaseapp.com',
    storageBucket: 'newstream-15e6a.firebasestorage.app',
    measurementId: 'G-3V6J0FJNB5',
  );

}